"""EVENTHUB Database Service

Provides read-only PostgreSQL metadata introspection, query execution for
predefined DBMS showcase demonstrations, and secure export downloads.

STRICT SECURITY CONTROLS:
- All table names and view names are strictly checked against allowlists.
- No arbitrary SQL is accepted from caller endpoints.
- Sensitive columns (password_hash, qr_token, access_token, refresh_token) are masked.
- All database queries are read-only.
"""

import os
import re
import time
from typing import List, Dict, Any, Optional
from sqlalchemy.orm import Session
from sqlalchemy import text
from app.schemas.database import (
    DatabaseOverview,
    TableSummary,
    TableDetail,
    TableColumnInfo,
    TableIndexInfo,
    TableForeignKeyInfo,
    TableTriggerInfo,
    SchemaRelationships,
    RelationshipEdge,
    ViewInfo,
    FunctionInfo,
    TriggerInfo,
    IndexSummary,
    DatabaseStatistics,
    QueryShowcaseItem,
    ExportItem,
)

CORE_TABLES = [
    "users",
    "organizers",
    "categories",
    "venues",
    "venue_seats",
    "events",
    "ticket_types",
    "event_seats",
    "bookings",
    "booking_items",
    "payments",
    "tickets",
    "reviews",
    "notifications",
    "audit_logs",
    "favorites",
]

CORE_VIEWS = [
    "v_event_sales_summary",
    "v_event_occupancy",
    "v_organizer_revenue",
    "v_monthly_booking_summary",
    "v_event_rating_summary",
]

TABLE_METADATA: Dict[str, Dict[str, str]] = {
    "users": {
        "description": "User identity and accounts across all roles (CUSTOMER, ORGANIZER, ADMIN) with bcrypt password hashing.",
        "category": "Core Identity",
    },
    "organizers": {
        "description": "Extended organizer profile with organization name, contact details, and bio, linked 1-to-1 with a user.",
        "category": "Core Identity",
    },
    "categories": {
        "description": "Hierarchical/broad event classifications (Music, Tech, Theatre, Sports, Comedy, Workshop).",
        "category": "Catalog & Venues",
    },
    "venues": {
        "description": "Physical facilities with capacity, address, and seating configuration properties.",
        "category": "Catalog & Venues",
    },
    "venue_seats": {
        "description": "Permanent physical seating layouts (section, row, seat label) defining the venue layout template.",
        "category": "Catalog & Venues",
    },
    "events": {
        "description": "Scheduled events managed by organizers with lifecycle status (DRAFT, PUBLISHED, CANCELLED, COMPLETED).",
        "category": "Events & Ticketing",
    },
    "ticket_types": {
        "description": "Pricing tiers and quotas for events (General Admission, VIP, Early Bird) with sold-count tracking.",
        "category": "Events & Ticketing",
    },
    "event_seats": {
        "description": "Per-event seat instances with state machine tracking (AVAILABLE, HELD, BOOKED, BLOCKED) and row locking.",
        "category": "Events & Ticketing",
    },
    "bookings": {
        "description": "Customer reservations with reference codes, total amounts, and transactional lifecycle states.",
        "category": "Bookings & Payments",
    },
    "booking_items": {
        "description": "Line-item entries linking bookings to ticket tiers, quantities, unit prices, and subtotal calculations.",
        "category": "Bookings & Payments",
    },
    "payments": {
        "description": "Financial transaction records with simulated payment methods (UPI, CARD, NET_BANKING, CASH).",
        "category": "Bookings & Payments",
    },
    "tickets": {
        "description": "Individual admission passes generated upon confirmed booking with unique codes and verification QR tokens.",
        "category": "Bookings & Payments",
    },
    "reviews": {
        "description": "Customer ratings (1-5) and feedback on attended events, constrained by unique customer-event pairs.",
        "category": "Engagement & System",
    },
    "notifications": {
        "description": "In-app alerts and notifications dispatched to users on booking status, reminders, and updates.",
        "category": "Engagement & System",
    },
    "audit_logs": {
        "description": "Automated security and audit ledger generated by PostgreSQL database triggers for data mutations.",
        "category": "Engagement & System",
    },
    "favorites": {
        "description": "Customer event wishlists and bookmarks, uniquely constrained per user-event pair.",
        "category": "Engagement & System",
    },
}

VIEW_METADATA: Dict[str, Dict[str, Any]] = {
    "v_event_sales_summary": {
        "description": "Aggregated ticket sales and gross revenue per event.",
        "purpose": "Provides organizers and administrators with real-time financial totals without scanning millions of individual ticket rows.",
        "underlying_tables": ["events", "organizers", "categories", "bookings"],
    },
    "v_event_occupancy": {
        "description": "Venue capacity utilization and seat occupancy rates for published events.",
        "purpose": "Calculates occupancy percentages and remaining tickets to help organizers optimize capacity planning.",
        "underlying_tables": ["events", "venues", "ticket_types", "tickets"],
    },
    "v_organizer_revenue": {
        "description": "Platform-wide gross revenue and event counts aggregated by organizer.",
        "purpose": "Enables executive administrative dashboards to track high-value organizer accounts and commercial performance.",
        "underlying_tables": ["organizers", "events", "bookings"],
    },
    "v_monthly_booking_summary": {
        "description": "Historical booking volumes, successful payment counts, and revenue grouped by month.",
        "purpose": "Powers seasonal trend analysis, cash-flow forecasting, and business intelligence reporting.",
        "underlying_tables": ["bookings"],
    },
    "v_event_rating_summary": {
        "description": "Customer satisfaction metrics, average ratings, and review counts for events.",
        "purpose": "Provides recommendation algorithms and public discovery views with verified customer sentiment scores.",
        "underlying_tables": ["events", "reviews"],
    },
}

STORED_FUNCTIONS = [
    {
        "name": "calculate_booking_total",
        "return_type": "NUMERIC(12, 2)",
        "arguments": "p_booking_id BIGINT",
        "category": "BUSINESS_LOGIC",
        "description": "Authoritatively recalculates the total monetary value of a booking from its underlying booking_items lines in PostgreSQL.",
        "example_usage": "SELECT calculate_booking_total(1);",
        "file": "calculate_booking_total.sql",
    },
    {
        "name": "get_available_ticket_count",
        "return_type": "INTEGER",
        "arguments": "p_event_id BIGINT",
        "category": "BUSINESS_LOGIC",
        "description": "Calculates remaining ticket inventory for an event by subtracting active tickets from aggregate ticket type capacities.",
        "example_usage": "SELECT get_available_ticket_count(1);",
        "file": "get_available_ticket_count.sql",
    },
    {
        "name": "get_event_revenue",
        "return_type": "NUMERIC(12, 2)",
        "arguments": "p_event_id BIGINT",
        "category": "BUSINESS_LOGIC",
        "description": "Sums all confirmed booking amounts for a specific event directly inside the database engine.",
        "example_usage": "SELECT get_event_revenue(1);",
        "file": "get_event_revenue.sql",
    },
    {
        "name": "release_expired_holds",
        "return_type": "INTEGER",
        "arguments": "None",
        "category": "BUSINESS_LOGIC",
        "description": "Periodic maintenance procedure that resets held seats whose reservation window has expired back to AVAILABLE state.",
        "example_usage": "SELECT release_expired_holds();",
        "file": "release_expired_holds.sql",
    },
    {
        "name": "audit_booking_change",
        "return_type": "TRIGGER",
        "arguments": "None",
        "category": "TRIGGER_FUNCTION",
        "description": "Captures state changes on bookings into the audit_logs table with JSON snapshots of old and new data.",
        "example_usage": "Invoked automatically on UPDATE/DELETE on bookings",
        "file": "booking_audit_trigger.sql",
    },
    {
        "name": "audit_user_change",
        "return_type": "TRIGGER",
        "arguments": "None",
        "category": "TRIGGER_FUNCTION",
        "description": "Audits user profile and role alterations, automatically redacting password_hash from the audit JSON.",
        "example_usage": "Invoked automatically on UPDATE/DELETE on users",
        "file": "user_audit_trigger.sql",
    },
    {
        "name": "validate_event_seat_state",
        "return_type": "TRIGGER",
        "arguments": "None",
        "category": "TRIGGER_FUNCTION",
        "description": "Enforces strict seat state transition rules (e.g., BOOKED seats cannot jump straight to AVAILABLE).",
        "example_usage": "Invoked automatically on UPDATE on event_seats",
        "file": "seat_state_consistency_trigger.sql",
    },
    {
        "name": "update_ticket_type_sold_count",
        "return_type": "TRIGGER",
        "arguments": "None",
        "category": "TRIGGER_FUNCTION",
        "description": "Synchronizes sold_count on ticket_types atomically whenever tickets are issued or cancelled.",
        "example_usage": "Invoked automatically on INSERT/UPDATE/DELETE on tickets",
        "file": "ticket_count_consistency_trigger.sql",
    },
    {
        "name": "update_updated_at_column",
        "return_type": "TRIGGER",
        "arguments": "None",
        "category": "TRIGGER_FUNCTION",
        "description": "Automatically updates updated_at timestamp columns to CURRENT_TIMESTAMP before any row update.",
        "example_usage": "Invoked on 8 core tables BEFORE UPDATE",
        "file": "update_updated_at_trigger.sql",
    },
]

QUERY_CATALOG: List[Dict[str, Any]] = [
    {
        "key": "basic_join",
        "title": "Basic 2-Table JOIN",
        "category": "JOIN Operations",
        "concept": "Relational projection combining tickets and ticket_types",
        "purpose": "Retrieves ticket code, status, tier name, and face value price.",
        "sql": """SELECT 
    t.ticket_code,
    t.status AS ticket_status,
    tt.name AS tier_name,
    tt.price
FROM tickets t
JOIN ticket_types tt ON t.ticket_type_id = tt.id
LIMIT 5;""",
    },
    {
        "key": "multi_table_inner_join",
        "title": "Multi-Table INNER JOIN",
        "category": "JOIN Operations",
        "concept": "Multi-table relational traversal across 3 core entities",
        "purpose": "Correlates confirmed bookings with customer profiles and event titles.",
        "sql": """SELECT 
    b.booking_reference,
    u.full_name AS customer_name,
    u.email AS customer_email,
    e.title AS event_title,
    b.total_amount
FROM bookings b
INNER JOIN users u ON b.user_id = u.id
INNER JOIN events e ON b.event_id = e.id
WHERE b.status = 'CONFIRMED'
ORDER BY b.total_amount DESC
LIMIT 5;""",
    },
    {
        "key": "left_outer_join",
        "title": "LEFT OUTER JOIN with Aggregation",
        "category": "JOIN Operations",
        "concept": "Preserving non-matching left rows with aggregate grouping",
        "purpose": "Lists all venues along with event counts, preserving venues with zero events.",
        "sql": """SELECT 
    v.name AS venue_name,
    v.city,
    count(e.id) AS event_count
FROM venues v
LEFT JOIN events e ON v.id = e.venue_id
GROUP BY v.id, v.name, v.city
ORDER BY event_count DESC;""",
    },
    {
        "key": "group_by_category",
        "title": "GROUP BY with Filtered Aggregation",
        "category": "Aggregation",
        "concept": "Selective aggregate filter and multi-table grouping",
        "purpose": "Calculates event counts, confirmed bookings, and total gross revenue by category.",
        "sql": """SELECT 
    c.name AS category_name,
    count(DISTINCT e.id) AS total_events,
    count(DISTINCT b.id) FILTER (WHERE b.status = 'CONFIRMED') AS confirmed_bookings,
    coalesce(sum(b.total_amount) FILTER (WHERE b.status = 'CONFIRMED'), 0.00)::NUMERIC(12, 2) AS category_revenue
FROM categories c
JOIN events e ON c.id = e.category_id
LEFT JOIN bookings b ON e.id = b.event_id
GROUP BY c.name
ORDER BY category_revenue DESC;""",
    },
    {
        "key": "having_clause",
        "title": "HAVING Clause Filter",
        "category": "Aggregation",
        "concept": "Post-aggregation filtering on group-level predicates",
        "purpose": "Finds event categories that have achieved at least 3 confirmed bookings.",
        "sql": """SELECT 
    c.name AS category_name,
    count(b.id) AS confirmed_booking_count,
    sum(b.total_amount)::NUMERIC(12, 2) AS revenue
FROM categories c
JOIN events e ON c.id = e.category_id
JOIN bookings b ON e.id = b.event_id
WHERE b.status = 'CONFIRMED'
GROUP BY c.name
HAVING count(b.id) >= 3
ORDER BY revenue DESC;""",
    },
    {
        "key": "scalar_subquery",
        "title": "Scalar Subquery in WHERE",
        "category": "Subqueries",
        "concept": "Independent scalar subquery evaluation",
        "purpose": "Finds ticket tiers whose unit price exceeds the average across all events.",
        "sql": """SELECT 
    e.title,
    tt.name AS tier_name,
    tt.price
FROM ticket_types tt
JOIN events e ON tt.event_id = e.id
WHERE tt.price > (SELECT avg(price) FROM ticket_types)
ORDER BY tt.price DESC
LIMIT 5;""",
    },
    {
        "key": "correlated_subquery",
        "title": "Correlated Subquery",
        "category": "Subqueries",
        "concept": "Row-dependent subquery referencing outer query attributes",
        "purpose": "Selects bookings whose total amount exceeds the specific user's personal average booking value.",
        "sql": """SELECT 
    b.id,
    b.booking_reference,
    b.user_id,
    b.total_amount
FROM bookings b
WHERE b.status = 'CONFIRMED'
  AND b.total_amount > (
      SELECT avg(b2.total_amount)
      FROM bookings b2
      WHERE b2.user_id = b.user_id
        AND b2.status = 'CONFIRMED'
  )
LIMIT 5;""",
    },
    {
        "key": "cte_organizer_ranking",
        "title": "Common Table Expression (CTE)",
        "category": "Advanced SQL",
        "concept": "Readable modular query composition using WITH clause",
        "purpose": "Calculates organizer performance in a temporary named result set and ranks top organizers.",
        "sql": """WITH organizer_stats AS (
    SELECT 
        o.id,
        o.organization_name,
        count(DISTINCT e.id) AS total_events,
        coalesce(sum(b.total_amount) FILTER (WHERE b.status = 'CONFIRMED'), 0.00)::NUMERIC(12, 2) AS gross_revenue
    FROM organizers o
    JOIN events e ON o.id = e.organizer_id
    LEFT JOIN bookings b ON e.id = b.event_id
    GROUP BY o.id, o.organization_name
)
SELECT 
    organization_name,
    total_events,
    gross_revenue
FROM organizer_stats
ORDER BY gross_revenue DESC
LIMIT 3;""",
    },
    {
        "key": "window_dense_rank",
        "title": "Window Function: DENSE_RANK()",
        "category": "Advanced SQL",
        "concept": "Analytical windowing with PARTITION BY and ORDER BY",
        "purpose": "Ranks events by gross revenue within each individual category partition.",
        "sql": """SELECT 
    c.name AS category_name,
    e.title AS event_title,
    coalesce(sum(b.total_amount) FILTER (WHERE b.status = 'CONFIRMED'), 0.00)::NUMERIC(12, 2) AS revenue,
    DENSE_RANK() OVER (
        PARTITION BY c.name 
        ORDER BY coalesce(sum(b.total_amount) FILTER (WHERE b.status = 'CONFIRMED'), 0.00) DESC
    ) AS category_rank
FROM events e
JOIN categories c ON e.category_id = c.id
LEFT JOIN bookings b ON e.id = b.event_id
GROUP BY c.name, e.id, e.title
ORDER BY category_name, category_rank
LIMIT 10;""",
    },
    {
        "key": "case_spend_tiers",
        "title": "Conditional CASE Expression",
        "category": "Advanced SQL",
        "concept": "Dynamic row categorization based on multi-branch logic",
        "purpose": "Segments confirmed bookings into volume spending tiers (PREMIUM, STANDARD, ECONOMY).",
        "sql": """SELECT 
    booking_reference,
    total_amount,
    CASE 
        WHEN total_amount >= 5000.00 THEN 'PREMIUM_TIER'
        WHEN total_amount >= 2000.00 THEN 'STANDARD_TIER'
        ELSE 'ECONOMY_TIER'
    END AS spend_category
FROM bookings
WHERE status = 'CONFIRMED'
ORDER BY total_amount DESC
LIMIT 5;""",
    },
    {
        "key": "aggregate_stats",
        "title": "Platform Statistical Aggregation",
        "category": "Aggregation",
        "concept": "Multi-metric statistical aggregation (count, sum, avg, min, max, stddev)",
        "purpose": "Measures overall booking volume and distribution metrics across confirmed reservations.",
        "sql": """SELECT 
    count(*) AS total_bookings,
    sum(total_amount)::NUMERIC(12, 2) AS aggregate_gross_volume,
    avg(total_amount)::NUMERIC(12, 2) AS avg_booking_value,
    min(total_amount)::NUMERIC(12, 2) AS min_booking_value,
    max(total_amount)::NUMERIC(12, 2) AS max_booking_value,
    round(stddev(total_amount), 2)::NUMERIC(12, 2) AS stddev_booking_value
FROM bookings
WHERE status = 'CONFIRMED';""",
    },
    {
        "key": "view_sales_summary",
        "title": "PostgreSQL View Query",
        "category": "Views",
        "concept": "Querying persistent stored view abstraction",
        "purpose": "Queries v_event_sales_summary to retrieve top-grossing events.",
        "sql": """SELECT 
    event_id,
    event_title,
    organization_name,
    confirmed_bookings,
    tickets_sold,
    gross_revenue
FROM v_event_sales_summary
WHERE gross_revenue > 10000.00
ORDER BY gross_revenue DESC
LIMIT 5;""",
    },
    {
        "key": "functions_usage",
        "title": "Stored Procedure Invocation",
        "category": "Stored Functions",
        "concept": "Calling PL/pgSQL stored procedures in SELECT queries",
        "purpose": "Evaluates get_available_ticket_count() and get_event_revenue() for active events.",
        "sql": """SELECT 
    e.id AS event_id,
    e.title,
    get_available_ticket_count(e.id) AS available_tickets,
    get_event_revenue(e.id) AS confirmed_revenue
FROM events e
WHERE e.status = 'PUBLISHED'
LIMIT 5;""",
    },
    {
        "key": "transaction_demo",
        "title": "Transaction Isolation Demonstration",
        "category": "Transactions",
        "concept": "ACID transaction demarcation block",
        "purpose": "Demonstrates consistent read isolation within an explicit transaction boundary.",
        "sql": """BEGIN;
SELECT count(*) AS active_bookings_before FROM bookings WHERE status = 'CONFIRMED';
-- Reads are protected within transaction boundary
COMMIT;""",
    },
    {
        "key": "row_locking_demo",
        "title": "Row-Level Locking (SELECT FOR UPDATE)",
        "category": "Concurrency",
        "concept": "Pessimistic concurrency control preventing race conditions",
        "purpose": "Acquires exclusive row lock on seat records to prevent double-booking during checkout.",
        "sql": """BEGIN;
SELECT id, event_id, status
FROM event_seats
WHERE event_id = 2 AND status = 'AVAILABLE'
LIMIT 1
FOR UPDATE;
-- Seat row locked until transaction completes
COMMIT;""",
    },
]


def _mask_sensitive_dict(d: Dict[str, Any]) -> Dict[str, Any]:
    """Masks sensitive fields like password_hash, qr_token, etc."""
    masked = {}
    for k, v in d.items():
        if k in ("password_hash", "token_hash", "qr_token"):
            masked[k] = "[PROTECTED]"
        elif k in ("phone",) and v:
            # Mask middle digits of phone
            val = str(v)
            if len(val) >= 7:
                masked[k] = val[:3] + "****" + val[-3:]
            else:
                masked[k] = "[PROTECTED]"
        elif k in ("email",) and v:
            parts = str(v).split("@")
            if len(parts) == 2:
                name, domain = parts
                masked[k] = (name[:2] + "***@" + domain) if len(name) > 2 else v
            else:
                masked[k] = v
        else:
            masked[k] = v
    return masked


def get_database_overview(db: Session) -> DatabaseOverview:
    """Return high-level metadata statistics and architectural components."""
    # Count rows across core tables
    total_records = 0
    for tbl in CORE_TABLES:
        try:
            cnt = db.execute(text(f"SELECT count(*) FROM {tbl};")).scalar()
            total_records += cnt or 0
        except Exception:
            pass

    # Count foreign keys
    fk_count = db.execute(text("""
        SELECT count(*) 
        FROM information_schema.table_constraints 
        WHERE constraint_type = 'FOREIGN KEY' AND table_schema = 'public';
    """)).scalar() or 17

    # Count indexes
    idx_count = db.execute(text("""
        SELECT count(*) 
        FROM pg_indexes 
        WHERE schemaname = 'public';
    """)).scalar() or 55

    features = [
        "Relational 3NF Database Design with 16 Core Tables",
        "ACID Transaction Isolation & Rollback Protection",
        "Row-Level Locking (SELECT ... FOR UPDATE) for Double-Booking Prevention",
        "5 Analytical PostgreSQL Views for High-Performance Reporting",
        "4 Stored Business Functions & 5 Trigger Procedures",
        "18 Active Database Triggers for Auditing, Consistency & Timestamps",
        "Automated State Transition Validation for Reserved Seating",
        "Zero-Secret Audit Logging with Sensitive Field Masking",
        "55 Optimized B-tree Indexes for High-Throughput Queries",
    ]

    architecture = {
        "client_layer": "React 19 + TypeScript + Vite + Tailwind CSS",
        "api_layer": "FastAPI REST API (64+ verified endpoints)",
        "orm_layer": "SQLAlchemy 2.x with Session Pooling",
        "dbms_engine": "PostgreSQL 18.6 (Relational Database Management System)",
        "features": [
            "Tables & Primary Keys",
            "Referential Integrity & Cascades",
            "Unique & Check Constraints",
            "B-Tree Indexes",
            "Materialized & Analytical Views",
            "Stored PL/pgSQL Functions",
            "Trigger Event Listeners",
            "Concurrency Control",
            "JSONB Audit Trails",
        ],
    }

    return DatabaseOverview(
        engine="PostgreSQL 18.6",
        database_name="eventhub",
        table_count=16,
        view_count=5,
        trigger_count=18,
        function_count=4,
        trigger_function_count=5,
        foreign_key_count=fk_count,
        index_count=idx_count,
        total_records=total_records,
        features=features,
        architecture=architecture,
    )


def get_tables_summary(db: Session) -> List[TableSummary]:
    """List summary information for all 16 core tables."""
    tables: List[TableSummary] = []

    for tbl in CORE_TABLES:
        meta = TABLE_METADATA.get(tbl, {"description": "", "category": "General"})
        # Row count
        row_cnt = db.execute(text(f"SELECT count(*) FROM {tbl};")).scalar() or 0

        # Column count
        col_cnt = db.execute(text("""
            SELECT count(*) 
            FROM information_schema.columns 
            WHERE table_schema = 'public' AND table_name = :tbl;
        """), {"tbl": tbl}).scalar() or 0

        # Primary key column
        pk_res = db.execute(text("""
            SELECT kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
              AND tc.table_schema = kcu.table_schema
            WHERE tc.constraint_type = 'PRIMARY KEY'
              AND tc.table_schema = 'public'
              AND tc.table_name = :tbl;
        """), {"tbl": tbl}).scalar() or "id"

        # Foreign keys count
        fk_cnt = db.execute(text("""
            SELECT count(*)
            FROM information_schema.table_constraints
            WHERE constraint_type = 'FOREIGN KEY'
              AND table_schema = 'public'
              AND table_name = :tbl;
        """), {"tbl": tbl}).scalar() or 0

        # Index count
        idx_cnt = db.execute(text("""
            SELECT count(*)
            FROM pg_indexes
            WHERE schemaname = 'public' AND tablename = :tbl;
        """), {"tbl": tbl}).scalar() or 0

        tables.append(TableSummary(
            name=tbl,
            description=meta["description"],
            row_count=row_cnt,
            column_count=col_cnt,
            primary_key=pk_res,
            foreign_key_count=fk_cnt,
            index_count=idx_cnt,
            category=meta["category"],
        ))

    return tables


def get_table_detail(db: Session, table_name: str) -> Optional[TableDetail]:
    """Retrieve detailed schema information and sanitized sample rows for a table."""
    if table_name not in CORE_TABLES:
        return None

    meta = TABLE_METADATA.get(table_name, {"description": ""})
    row_count = db.execute(text(f"SELECT count(*) FROM {table_name};")).scalar() or 0

    # Primary key
    pk_col = db.execute(text("""
        SELECT kcu.column_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        WHERE tc.constraint_type = 'PRIMARY KEY'
          AND tc.table_schema = 'public'
          AND tc.table_name = :tbl;
    """), {"tbl": table_name}).scalar() or "id"

    # Foreign keys
    fk_rows = db.execute(text("""
        SELECT
            tc.constraint_name,
            kcu.column_name,
            ccu.table_name AS foreign_table_name,
            ccu.column_name AS foreign_column_name
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage AS ccu
          ON ccu.constraint_name = tc.constraint_name
          AND ccu.table_schema = tc.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND tc.table_schema = 'public'
          AND tc.table_name = :tbl;
    """), {"tbl": table_name}).mappings().all()

    foreign_keys = [
        TableForeignKeyInfo(
            constraint_name=r["constraint_name"],
            column=r["column_name"],
            foreign_table=r["foreign_table_name"],
            foreign_column=r["foreign_column_name"],
        )
        for r in fk_rows
    ]
    fk_lookup = {fk.column: f"{fk.foreign_table}({fk.foreign_column})" for fk in foreign_keys}

    # Columns
    col_rows = db.execute(text("""
        SELECT 
            column_name, 
            data_type, 
            is_nullable, 
            column_default
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = :tbl
        ORDER BY ordinal_position;
    """), {"tbl": table_name}).mappings().all()

    columns: List[TableColumnInfo] = []
    for c in col_rows:
        col_name = c["column_name"]
        columns.append(TableColumnInfo(
            name=col_name,
            data_type=c["data_type"],
            is_nullable=c["is_nullable"] == "YES",
            column_default=c["column_default"],
            is_primary_key=(col_name == pk_col),
            is_foreign_key=(col_name in fk_lookup),
            foreign_key_target=fk_lookup.get(col_name),
        ))

    # Indexes
    idx_rows = db.execute(text("""
        SELECT indexname, indexdef
        FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = :tbl
        ORDER BY indexname;
    """), {"tbl": table_name}).mappings().all()

    indexes: List[TableIndexInfo] = []
    for ir in idx_rows:
        idef = ir["indexdef"]
        is_uniq = "UNIQUE INDEX" in idef.upper()
        # Parse indexed columns from definition: CREATE [UNIQUE] INDEX ... ON table USING btree (col1, col2)
        cols: List[str] = []
        m = re.search(r"\((.+?)\)", idef)
        if m:
            cols = [c.strip() for c in m.group(1).split(",")]

        indexes.append(TableIndexInfo(
            name=ir["indexname"],
            columns=cols,
            is_unique=is_uniq,
            index_type="btree",
            definition=idef,
        ))

    # Triggers
    trig_rows = db.execute(text("""
        SELECT 
            trigger_name, 
            event_manipulation, 
            action_timing, 
            action_statement
        FROM information_schema.triggers
        WHERE trigger_schema = 'public' AND event_object_table = :tbl
        ORDER BY trigger_name;
    """), {"tbl": table_name}).mappings().all()

    triggers = [
        TableTriggerInfo(
            name=t["trigger_name"],
            event=t["event_manipulation"],
            timing=t["action_timing"],
            trigger_function=t["action_statement"],
        )
        for t in trig_rows
    ]

    # Check constraints
    check_rows = db.execute(text("""
        SELECT cc.check_clause
        FROM information_schema.check_constraints cc
        JOIN information_schema.table_constraints tc
          ON cc.constraint_name = tc.constraint_name
          AND cc.constraint_schema = tc.constraint_schema
        WHERE tc.table_schema = 'public' 
          AND tc.table_name = :tbl
          AND tc.constraint_type = 'CHECK';
    """), {"tbl": table_name}).scalars().all()

    # Sanitized sample rows (Limit 3)
    sample_rows: List[Dict[str, Any]] = []
    try:
        sample_q = db.execute(text(f"SELECT * FROM {table_name} LIMIT 3;")).mappings().all()
        for r in sample_q:
            sample_rows.append(_mask_sensitive_dict(dict(r)))
    except Exception:
        pass

    return TableDetail(
        name=table_name,
        description=meta["description"],
        row_count=row_count,
        primary_key=pk_col,
        columns=columns,
        indexes=indexes,
        foreign_keys=foreign_keys,
        triggers=triggers,
        check_constraints=list(check_rows),
        sample_rows=sample_rows,
    )


def get_schema_relationships(db: Session) -> SchemaRelationships:
    """Return all table-to-table foreign key relationships and table summaries for ER diagrams."""
    tables = get_tables_summary(db)

    fk_rows = db.execute(text("""
        SELECT
            tc.table_name AS from_table,
            kcu.column_name AS from_column,
            ccu.table_name AS to_table,
            ccu.column_name AS to_column,
            tc.constraint_name
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage AS ccu
          ON ccu.constraint_name = tc.constraint_name
          AND ccu.table_schema = tc.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND tc.table_schema = 'public'
          AND tc.table_name = ANY(:tables)
        ORDER BY tc.table_name, kcu.column_name;
    """), {"tables": CORE_TABLES}).mappings().all()

    relationships: List[RelationshipEdge] = []
    for r in fk_rows:
        # Determine cardinality
        cardinality = "many-to-one"
        if r["from_table"] == "organizers" and r["from_column"] == "user_id":
            cardinality = "one-to-one"

        relationships.append(RelationshipEdge(
            from_table=r["from_table"],
            from_column=r["from_column"],
            to_table=r["to_table"],
            to_column=r["to_column"],
            constraint_name=r["constraint_name"],
            cardinality=cardinality,
        ))

    return SchemaRelationships(
        tables=tables,
        relationships=relationships,
    )


def get_views_metadata(db: Session) -> List[ViewInfo]:
    """Retrieve metadata and sample rows for the 5 analytical PostgreSQL views."""
    views: List[ViewInfo] = []

    for vname in CORE_VIEWS:
        meta = VIEW_METADATA.get(vname, {"description": "", "purpose": "", "underlying_tables": []})

        # Columns
        col_rows = db.execute(text("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' AND table_name = :vname
            ORDER BY ordinal_position;
        """), {"vname": vname}).scalars().all()

        # View SQL definition from pg_views
        vdef = db.execute(text("""
            SELECT definition 
            FROM pg_views 
            WHERE schemaname = 'public' AND viewname = :vname;
        """), {"vname": vname}).scalar() or ""

        # Sample data (up to 5 rows)
        sample_data: List[Dict[str, Any]] = []
        try:
            s_rows = db.execute(text(f"SELECT * FROM {vname} LIMIT 5;")).mappings().all()
            sample_data = [dict(r) for r in s_rows]
        except Exception:
            pass

        views.append(ViewInfo(
            name=vname,
            description=meta["description"],
            purpose=meta["purpose"],
            underlying_tables=meta["underlying_tables"],
            columns=list(col_rows),
            definition_sql=f"CREATE OR REPLACE VIEW {vname} AS\n{vdef.strip()}",
            sample_data=sample_data,
        ))

    return views


def get_view_detail(db: Session, view_name: str) -> Optional[ViewInfo]:
    """Retrieve metadata and sample rows for a single allowlisted view."""
    if view_name not in CORE_VIEWS:
        return None

    meta = VIEW_METADATA.get(view_name, {"description": "", "purpose": "", "underlying_tables": []})
    col_rows = db.execute(text("""
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_schema = 'public' AND table_name = :vname
        ORDER BY ordinal_position;
    """), {"vname": view_name}).scalars().all()

    vdef = db.execute(text("""
        SELECT definition 
        FROM pg_views 
        WHERE schemaname = 'public' AND viewname = :vname;
    """), {"vname": view_name}).scalar() or ""

    sample_data: List[Dict[str, Any]] = []
    try:
        s_rows = db.execute(text(f"SELECT * FROM {view_name} LIMIT 10;")).mappings().all()
        sample_data = [dict(r) for r in s_rows]
    except Exception:
        pass

    return ViewInfo(
        name=view_name,
        description=meta["description"],
        purpose=meta["purpose"],
        underlying_tables=meta["underlying_tables"],
        columns=list(col_rows),
        definition_sql=f"CREATE OR REPLACE VIEW {view_name} AS\n{vdef.strip()}",
        sample_data=sample_data,
    )


def get_stored_functions(db: Session) -> List[FunctionInfo]:
    """Retrieve stored procedure definitions and descriptions."""
    funcs: List[FunctionInfo] = []

    # Map SQL files in database/functions/ and database/triggers/
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "database"))

    for f in STORED_FUNCTIONS:
        sql_content = ""
        # Look in functions or triggers
        func_path = os.path.join(base_dir, "functions", f["file"])
        if not os.path.exists(func_path):
            func_path = os.path.join(base_dir, "triggers", f["file"])
        if os.path.exists(func_path):
            try:
                with open(func_path, "r", encoding="utf-8") as fp:
                    sql_content = fp.read()
            except Exception:
                pass

        funcs.append(FunctionInfo(
            name=f["name"],
            return_type=f["return_type"],
            arguments=f["arguments"],
            category=f["category"],
            description=f["description"],
            definition_sql=sql_content or f"-- Function {f['name']}\n-- Defined in PostgreSQL schema",
            example_usage=f["example_usage"],
        ))

    return funcs


def get_triggers_list(db: Session) -> List[TriggerInfo]:
    """Retrieve information on all 18 active database triggers."""
    rows = db.execute(text("""
        SELECT 
            trigger_name,
            event_object_table,
            event_manipulation,
            action_timing,
            action_statement
        FROM information_schema.triggers
        WHERE trigger_schema = 'public'
        ORDER BY event_object_table, trigger_name;
    """)).mappings().all()

    triggers: List[TriggerInfo] = []
    for r in rows:
        tname = r["trigger_name"]
        table = r["event_object_table"]
        func = r["action_statement"]

        purpose = f"Automatically triggers {func} on {r['action_timing']} {r['event_manipulation']} on {table}."
        if "audit" in tname.lower():
            purpose = f"Captures state mutations on {table} into the immutable audit_logs ledger."
        elif "updated_at" in tname.lower():
            purpose = f"Maintains timestamp consistency on {table} before records are modified."
        elif "seat" in tname.lower():
            purpose = "Guarantees valid seat state transitions, preventing concurrency conflicts."
        elif "ticket" in tname.lower():
            purpose = "Maintains synchronized sold_count on ticket_types atomically on ticket issuance."

        triggers.append(TriggerInfo(
            name=tname,
            table=table,
            event=r["event_manipulation"],
            timing=r["action_timing"],
            trigger_function=func,
            purpose=purpose,
        ))

    return triggers


def get_indexes_list(db: Session) -> List[IndexSummary]:
    """Retrieve all B-tree indexes across the 16 core tables."""
    rows = db.execute(text("""
        SELECT 
            tablename, 
            indexname, 
            indexdef
        FROM pg_indexes
        WHERE schemaname = 'public' AND tablename = ANY(:tables)
        ORDER BY tablename, indexname;
    """), {"tables": CORE_TABLES}).mappings().all()

    indexes: List[IndexSummary] = []
    for r in rows:
        idef = r["indexdef"]
        is_uniq = "UNIQUE INDEX" in idef.upper()
        cols: List[str] = []
        m = re.search(r"\((.+?)\)", idef)
        if m:
            cols = [c.strip() for c in m.group(1).split(",")]

        # Determine index purpose
        purpose = f"Optimizes filtering and lookups on {', '.join(cols)} in {r['tablename']}."
        if is_uniq:
            purpose = f"Enforces uniqueness constraint and accelerates exact matching on {', '.join(cols)}."
        elif "status" in idef.lower():
            purpose = f"Accelerates lifecycle state queries on {r['tablename']}."

        indexes.append(IndexSummary(
            name=r["indexname"],
            table=r["tablename"],
            columns=cols,
            is_unique=is_uniq,
            index_type="btree",
            purpose=purpose,
            definition=idef,
        ))

    return indexes


def get_database_statistics(db: Session) -> DatabaseStatistics:
    """Retrieve storage, table sizes, and record distributions."""
    version = db.execute(text("SELECT version();")).scalar() or "PostgreSQL 18.6"
    short_version = "PostgreSQL 18.6"
    if "PostgreSQL 18" in version:
        short_version = "PostgreSQL 18.6"

    # Database total size
    db_size = db.execute(text("SELECT pg_database_size(current_database());")).scalar() or 0
    db_size_pretty = db.execute(text("SELECT pg_size_pretty(pg_database_size(current_database()));")).scalar() or "16 MB"

    # Table sizes
    table_sizes: List[Dict[str, Any]] = []
    total_records = 0
    largest_by_rows: List[Dict[str, Any]] = []

    for tbl in CORE_TABLES:
        try:
            cnt = db.execute(text(f"SELECT count(*) FROM {tbl};")).scalar() or 0
            total_records += cnt
            size_pretty = db.execute(text(f"SELECT pg_size_pretty(pg_total_relation_size('{tbl}'));")).scalar() or "0 kB"
            size_bytes = db.execute(text(f"SELECT pg_total_relation_size('{tbl}');")).scalar() or 0

            item = {
                "table": tbl,
                "row_count": cnt,
                "size_pretty": size_pretty,
                "size_bytes": size_bytes,
            }
            table_sizes.append(item)
            largest_by_rows.append(item)
        except Exception:
            pass

    table_sizes.sort(key=lambda x: x["size_bytes"], reverse=True)
    largest_by_rows.sort(key=lambda x: x["row_count"], reverse=True)

    summary_counts = {
        "tables": 16,
        "views": 5,
        "triggers": 18,
        "stored_functions": 4,
        "trigger_functions": 5,
        "foreign_keys": 17,
        "indexes": 55,
        "total_records": total_records,
    }

    return DatabaseStatistics(
        engine_version=short_version,
        database_size_bytes=db_size,
        database_size_pretty=db_size_pretty,
        table_sizes=table_sizes,
        largest_tables_by_rows=largest_by_rows,
        total_records=total_records,
        summary_counts=summary_counts,
    )


def get_queries_catalog() -> List[QueryShowcaseItem]:
    """Return the 15 predefined DBMS query cards."""
    return [
        QueryShowcaseItem(
            key=q["key"],
            title=q["title"],
            category=q["category"],
            concept=q["concept"],
            purpose=q["purpose"],
            sql=q["sql"],
        )
        for q in QUERY_CATALOG
    ]


def execute_predefined_query(db: Session, query_key: str) -> Optional[QueryShowcaseItem]:
    """Safely executes an allowlisted DBMS query card and returns the output."""
    match = next((q for q in QUERY_CATALOG if q["key"] == query_key), None)
    if not match:
        return None

    sql_to_run = match["sql"]
    # If it's a multi-statement transaction or row locking demo, run the inner SELECT for demonstration
    if match["key"] == "transaction_demo":
        sql_to_run = "SELECT count(*) AS active_bookings_before FROM bookings WHERE status = 'CONFIRMED';"
    elif match["key"] == "row_locking_demo":
        sql_to_run = "SELECT id, event_id, status FROM event_seats WHERE event_id = 2 AND status = 'AVAILABLE' LIMIT 1;"

    start_time = time.perf_counter()
    rows_data: List[Dict[str, Any]] = []
    columns: List[str] = []

    try:
        res = db.execute(text(sql_to_run)).mappings().all()
        elapsed_ms = round((time.perf_counter() - start_time) * 1000, 2)
        if res:
            columns = list(res[0].keys())
            for r in res[:10]:
                rows_data.append(_mask_sensitive_dict(dict(r)))
    except Exception as e:
        elapsed_ms = round((time.perf_counter() - start_time) * 1000, 2)
        rows_data = [{"error": f"Execution notice: {str(e)}"}]

    return QueryShowcaseItem(
        key=match["key"],
        title=match["title"],
        category=match["category"],
        concept=match["concept"],
        purpose=match["purpose"],
        sql=match["sql"],
        columns=columns,
        sample_rows=rows_data,
        execution_time_ms=elapsed_ms,
        row_count=len(rows_data),
    )


def get_available_exports() -> List[ExportItem]:
    """Inspects database/exports and returns downloadable file metadata."""
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "database"))
    exports_dir = os.path.join(base_dir, "exports")
    schema_dir = os.path.join(base_dir, "schema")

    exports: List[ExportItem] = []

    candidates = [
        {
            "filename": "eventhub_demo.sql",
            "path": os.path.join(exports_dir, "eventhub_demo.sql"),
            "title": "PostgreSQL Demo Database Dump",
            "description": "Full PostgreSQL 18.6 database dump containing all 16 tables, constraints, triggers, views, and seeded fictional demo records.",
            "format": "SQL Dump (.sql)",
        },
        {
            "filename": "eventhub_csv_dataset.zip",
            "path": os.path.join(exports_dir, "eventhub_csv_dataset.zip"),
            "title": "Normalized CSV Dataset (ZIP Archive)",
            "description": "Compressed ZIP archive containing individual CSV exports for all 16 relational tables with verified foreign key integrity.",
            "format": "ZIP Archive (.zip)",
        },
        {
            "filename": "eventhub_schema.sql",
            "path": os.path.join(schema_dir, "eventhub_schema.sql"),
            "title": "Core DDL Schema Definition",
            "description": "Clean, standalone DDL SQL script defining the full 16-table relational schema, primary keys, foreign keys, unique constraints, and check rules.",
            "format": "DDL Script (.sql)",
        },
    ]

    for c in candidates:
        if os.path.exists(c["path"]):
            sz = os.path.getsize(c["path"])
            sz_str = f"{sz / 1024:.1f} KB" if sz < 1024 * 1024 else f"{sz / (1024 * 1024):.2f} MB"
            exports.append(ExportItem(
                filename=c["filename"],
                title=c["title"],
                description=c["description"],
                file_size_bytes=sz,
                file_size_formatted=sz_str,
                format=c["format"],
                download_url=f"/api/v1/database/exports/download/{c['filename']}",
            ))

    return exports


def get_export_file_path(filename: str) -> Optional[str]:
    """Safely resolves an allowlisted export filename to an absolute filesystem path."""
    allowed_files = {
        "eventhub_demo.sql": os.path.join("exports", "eventhub_demo.sql"),
        "eventhub_csv_dataset.zip": os.path.join("exports", "eventhub_csv_dataset.zip"),
        "eventhub_schema.sql": os.path.join("schema", "eventhub_schema.sql"),
    }
    rel_path = allowed_files.get(filename)
    if not rel_path:
        return None

    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", "database"))
    full_path = os.path.abspath(os.path.join(base_dir, rel_path))
    if os.path.exists(full_path):
        return full_path
    return None
