"""create_core_16_tables

Revision ID: 171a3cddf5ff
Revises: 
Create Date: 2026-10-01 21:05:18.128819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '171a3cddf5ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('CUSTOMER', 'ORGANIZER', 'ADMIN')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('venues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address_line', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_venues_capacity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_venues_city', 'venues', ['city'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('organizers',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('venue_seats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('row_label', sa.String(length=20), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_label', sa.String(length=50), nullable=False),
    sa.Column('seat_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.CheckConstraint('seat_number > 0', name='ck_venue_seats_seat_number'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'seat_label', name='uq_venue_seats_venue_label')
    )
    op.create_index('ix_venue_seats_venue_id', 'venue_seats', ['venue_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('organizer_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('seating_mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('banner_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("seating_mode IN ('GENERAL_ADMISSION', 'RESERVED_SEATING')", name='ck_events_seating_mode'),
    sa.CheckConstraint("status IN ('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED')", name='ck_events_status'),
    sa.CheckConstraint('end_time IS NULL OR end_time > start_time', name='ck_events_end_time_after_start'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_events_category_id', 'events', ['category_id'], unique=False)
    op.create_index('ix_events_event_date', 'events', ['event_date'], unique=False)
    op.create_index('ix_events_organizer_id', 'events', ['organizer_id'], unique=False)
    op.create_index('ix_events_venue_id', 'events', ['venue_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('booking_reference', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'REFUNDED')", name='ck_bookings_status'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_bookings_discount_amount'),
    sa.CheckConstraint('subtotal >= 0', name='ck_bookings_subtotal'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_bookings_tax_amount'),
    sa.CheckConstraint('total_amount >= 0', name='ck_bookings_total_amount'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index('ix_bookings_event_id', 'bookings', ['event_id'], unique=False)
    op.create_index('ix_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_favorites_user_event')
    )
    op.create_index('ix_favorites_event_id', 'favorites', ['event_id'], unique=False)
    op.create_index('ix_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_reviews_user_event')
    )
    op.create_index('ix_reviews_event_id', 'reviews', ['event_id'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('ticket_types',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('sold_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sale_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_ticket_types_capacity'),
    sa.CheckConstraint('price >= 0', name='ck_ticket_types_price'),
    sa.CheckConstraint('sold_count <= capacity', name='ck_ticket_types_sold_count_max'),
    sa.CheckConstraint('sold_count >= 0', name='ck_ticket_types_sold_count_min'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_types_event_id', 'ticket_types', ['event_id'], unique=False)
    op.create_table('booking_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_type_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_booking_items_quantity'),
    sa.CheckConstraint('subtotal >= 0', name='ck_booking_items_subtotal'),
    sa.CheckConstraint('unit_price >= 0', name='ck_booking_items_unit_price'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_items_booking_id', 'booking_items', ['booking_id'], unique=False)
    op.create_index('ix_booking_items_ticket_type_id', 'booking_items', ['ticket_type_id'], unique=False)
    op.create_table('event_seats',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_seat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('held_by_booking_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED')", name='ck_event_seats_status'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['held_by_booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_seat_id'], ['venue_seats.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'venue_seat_id', name='uq_event_seats_event_seat')
    )
    op.create_index('ix_event_seats_event_status', 'event_seats', ['event_id', 'status'], unique=False)
    op.create_index('ix_event_seats_held_by_booking_id', 'event_seats', ['held_by_booking_id'], unique=False)
    op.create_index('ix_event_seats_venue_seat_id', 'event_seats', ['venue_seat_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('UPI', 'CARD', 'NET_BANKING', 'CASH')", name='ck_payments_payment_method'),
    sa.CheckConstraint("status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')", name='ck_payments_status'),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_type_id', sa.BigInteger(), nullable=False),
    sa.Column('event_seat_id', sa.BigInteger(), nullable=True),
    sa.Column('ticket_code', sa.String(length=100), nullable=False),
    sa.Column('qr_token', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'USED', 'CANCELLED', 'REFUNDED')", name='ck_tickets_status'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_seat_id'], ['event_seats.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_index('ix_tickets_booking_id', 'tickets', ['booking_id'], unique=False)
    op.create_index('ix_tickets_event_seat_id', 'tickets', ['event_seat_id'], unique=False)
    op.create_index('ix_tickets_ticket_type_id', 'tickets', ['ticket_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_ticket_type_id', table_name='tickets')
    op.drop_index('ix_tickets_event_seat_id', table_name='tickets')
    op.drop_index('ix_tickets_booking_id', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_event_seats_venue_seat_id', table_name='event_seats')
    op.drop_index('ix_event_seats_held_by_booking_id', table_name='event_seats')
    op.drop_index('ix_event_seats_event_status', table_name='event_seats')
    op.drop_table('event_seats')
    op.drop_index('ix_booking_items_ticket_type_id', table_name='booking_items')
    op.drop_index('ix_booking_items_booking_id', table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index('ix_ticket_types_event_id', table_name='ticket_types')
    op.drop_table('ticket_types')
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_event_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_favorites_user_id', table_name='favorites')
    op.drop_index('ix_favorites_event_id', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('ix_bookings_user_id', table_name='bookings')
    op.drop_index('ix_bookings_event_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_events_venue_id', table_name='events')
    op.drop_index('ix_events_organizer_id', table_name='events')
    op.drop_index('ix_events_event_date', table_name='events')
    op.drop_index('ix_events_category_id', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_venue_seats_venue_id', table_name='venue_seats')
    op.drop_table('venue_seats')
    op.drop_table('organizers')
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_venues_city', table_name='venues')
    op.drop_table('venues')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
