-- ============================================================================
-- EVENTHUB — Core Relational Database Schema DDL
-- Database Engine: PostgreSQL 18.6+
-- Phase: 2 (Database Foundation)
-- Tables: 16 Core Entities
-- Seed Data: None (Schema definition only)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. USERS
-- Core identity and actor table for customers, organizers, and administrators.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'ORGANIZER', 'ADMIN'))
);

-- ----------------------------------------------------------------------------
-- 2. ORGANIZERS
-- Extended organization profile associated 1-to-1 with a user entity.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS organizers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    organization_name VARCHAR(150) NOT NULL,
    description TEXT,
    contact_email VARCHAR(150),
    contact_phone VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_organizers_user_id FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE RESTRICT
);

-- ----------------------------------------------------------------------------
-- 3. CATEGORIES
-- Taxonomy and categorization for events.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------------------
-- 4. VENUES
-- Physical or structured venues hosting events.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    address_line VARCHAR(250) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_venues_capacity CHECK (capacity > 0)
);

CREATE INDEX IF NOT EXISTS ix_venues_city ON venues (city);

-- ----------------------------------------------------------------------------
-- 5. VENUE_SEATS
-- Physical seating blueprint / seat topology within a venue.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS venue_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id BIGINT NOT NULL,
    section_name VARCHAR(100) NOT NULL,
    row_label VARCHAR(20) NOT NULL,
    seat_number INTEGER NOT NULL,
    seat_label VARCHAR(50) NOT NULL,
    seat_type VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_venue_seats_seat_number CHECK (seat_number > 0),
    CONSTRAINT uq_venue_seats_venue_label UNIQUE (venue_id, seat_label),
    CONSTRAINT fk_venue_seats_venue_id FOREIGN KEY (venue_id) 
        REFERENCES venues (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_venue_seats_venue_id ON venue_seats (venue_id);

-- ----------------------------------------------------------------------------
-- 6. EVENTS
-- Core event listings managed by organizers, categorized and hosted at venues.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    venue_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    slug VARCHAR(220) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    event_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME,
    seating_mode VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    banner_image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_events_seating_mode CHECK (seating_mode IN ('GENERAL_ADMISSION', 'RESERVED_SEATING')),
    CONSTRAINT ck_events_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT ck_events_end_time_after_start CHECK (end_time IS NULL OR end_time > start_time),
    CONSTRAINT fk_events_organizer_id FOREIGN KEY (organizer_id) 
        REFERENCES organizers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_category_id FOREIGN KEY (category_id) 
        REFERENCES categories (id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_venue_id FOREIGN KEY (venue_id) 
        REFERENCES venues (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_events_event_date ON events (event_date);
CREATE INDEX IF NOT EXISTS ix_events_category_id ON events (category_id);
CREATE INDEX IF NOT EXISTS ix_events_organizer_id ON events (organizer_id);
CREATE INDEX IF NOT EXISTS ix_events_venue_id ON events (venue_id);

-- ----------------------------------------------------------------------------
-- 7. TICKET_TYPES
-- Ticket tiers and inventory for events (e.g., VIP, General Admission, Early Bird).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ticket_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price NUMERIC(12, 2) NOT NULL,
    capacity INTEGER NOT NULL,
    sold_count INTEGER NOT NULL DEFAULT 0,
    sale_start TIMESTAMP WITH TIME ZONE,
    sale_end TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ticket_types_price CHECK (price >= 0),
    CONSTRAINT ck_ticket_types_capacity CHECK (capacity > 0),
    CONSTRAINT ck_ticket_types_sold_count_min CHECK (sold_count >= 0),
    CONSTRAINT ck_ticket_types_sold_count_max CHECK (sold_count <= capacity),
    CONSTRAINT fk_ticket_types_event_id FOREIGN KEY (event_id) 
        REFERENCES events (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_ticket_types_event_id ON ticket_types (event_id);

-- ----------------------------------------------------------------------------
-- 8. BOOKINGS
-- Transactional reservations initiated by users for an event.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    booking_reference VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(12, 2) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_bookings_status CHECK (status IN ('PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'EXPIRED', 'REFUNDED')),
    CONSTRAINT ck_bookings_subtotal CHECK (subtotal >= 0),
    CONSTRAINT ck_bookings_discount_amount CHECK (discount_amount >= 0),
    CONSTRAINT ck_bookings_tax_amount CHECK (tax_amount >= 0),
    CONSTRAINT ck_bookings_total_amount CHECK (total_amount >= 0),
    CONSTRAINT fk_bookings_user_id FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_bookings_event_id FOREIGN KEY (event_id) 
        REFERENCES events (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_bookings_user_id ON bookings (user_id);
CREATE INDEX IF NOT EXISTS ix_bookings_event_id ON bookings (event_id);

-- ----------------------------------------------------------------------------
-- 9. EVENT_SEATS
-- Real-time seat allocation, state management, and hold concurrency for events.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    venue_seat_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    hold_expires_at TIMESTAMP WITH TIME ZONE,
    held_by_booking_id BIGINT,
    CONSTRAINT ck_event_seats_status CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED')),
    CONSTRAINT uq_event_seats_event_seat UNIQUE (event_id, venue_seat_id),
    CONSTRAINT fk_event_seats_event_id FOREIGN KEY (event_id) 
        REFERENCES events (id) ON DELETE RESTRICT,
    CONSTRAINT fk_event_seats_venue_seat_id FOREIGN KEY (venue_seat_id) 
        REFERENCES venue_seats (id) ON DELETE RESTRICT,
    CONSTRAINT fk_event_seats_held_by_booking_id FOREIGN KEY (held_by_booking_id) 
        REFERENCES bookings (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_event_seats_event_status ON event_seats (event_id, status);
CREATE INDEX IF NOT EXISTS ix_event_seats_held_by_booking_id ON event_seats (held_by_booking_id);
CREATE INDEX IF NOT EXISTS ix_event_seats_venue_seat_id ON event_seats (venue_seat_id);

-- ----------------------------------------------------------------------------
-- 10. BOOKING_ITEMS
-- Granular line items inside each booking indicating quantities per ticket type.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS booking_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    ticket_type_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    CONSTRAINT ck_booking_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_booking_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_booking_items_subtotal CHECK (subtotal >= 0),
    CONSTRAINT fk_booking_items_booking_id FOREIGN KEY (booking_id) 
        REFERENCES bookings (id) ON DELETE RESTRICT,
    CONSTRAINT fk_booking_items_ticket_type_id FOREIGN KEY (ticket_type_id) 
        REFERENCES ticket_types (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_booking_items_booking_id ON booking_items (booking_id);
CREATE INDEX IF NOT EXISTS ix_booking_items_ticket_type_id ON booking_items (ticket_type_id);

-- ----------------------------------------------------------------------------
-- 11. PAYMENTS
-- Financial transactions linked to bookings. (Simulated payment records)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    transaction_reference VARCHAR(100) NOT NULL UNIQUE,
    amount NUMERIC(12, 2) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_payments_amount CHECK (amount >= 0),
    CONSTRAINT ck_payments_payment_method CHECK (payment_method IN ('UPI', 'CARD', 'NET_BANKING', 'CASH')),
    CONSTRAINT ck_payments_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED')),
    CONSTRAINT fk_payments_booking_id FOREIGN KEY (booking_id) 
        REFERENCES bookings (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_payments_booking_id ON payments (booking_id);

-- ----------------------------------------------------------------------------
-- 12. TICKETS
-- Issued individual admissions with unique barcodes/QR tokens.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    ticket_type_id BIGINT NOT NULL,
    event_seat_id BIGINT,
    ticket_code VARCHAR(100) NOT NULL UNIQUE,
    qr_token VARCHAR(150) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    checked_in_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_tickets_status CHECK (status IN ('ACTIVE', 'USED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT fk_tickets_booking_id FOREIGN KEY (booking_id) 
        REFERENCES bookings (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tickets_ticket_type_id FOREIGN KEY (ticket_type_id) 
        REFERENCES ticket_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_tickets_event_seat_id FOREIGN KEY (event_seat_id) 
        REFERENCES event_seats (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_tickets_booking_id ON tickets (booking_id);
CREATE INDEX IF NOT EXISTS ix_tickets_ticket_type_id ON tickets (ticket_type_id);
CREATE INDEX IF NOT EXISTS ix_tickets_event_seat_id ON tickets (event_seat_id);

-- ----------------------------------------------------------------------------
-- 13. REVIEWS
-- Attendee feedback and numerical ratings for completed events.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_reviews_rating_range CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uq_reviews_user_event UNIQUE (user_id, event_id),
    CONSTRAINT fk_reviews_user_id FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reviews_event_id FOREIGN KEY (event_id) 
        REFERENCES events (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_reviews_event_id ON reviews (event_id);
CREATE INDEX IF NOT EXISTS ix_reviews_user_id ON reviews (user_id);

-- ----------------------------------------------------------------------------
-- 14. NOTIFICATIONS
-- Direct user notifications regarding bookings, event updates, and system alerts.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_notifications_user_id_is_read ON notifications (user_id, is_read);

-- ----------------------------------------------------------------------------
-- 15. AUDIT_LOGS
-- Comprehensive system audit trail capturing state modifications.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    old_data JSONB,
    new_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user_id FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at ON audit_logs (created_at);

-- ----------------------------------------------------------------------------
-- 16. FAVORITES
-- Bookmarked/wishlisted events saved by users.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_favorites_user_event UNIQUE (user_id, event_id),
    CONSTRAINT fk_favorites_user_id FOREIGN KEY (user_id) 
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_favorites_event_id FOREIGN KEY (event_id) 
        REFERENCES events (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_favorites_event_id ON favorites (event_id);
CREATE INDEX IF NOT EXISTS ix_favorites_user_id ON favorites (user_id);
